print("Course" + "                                    " + "Credits")
print("High Performance Computing" + "                      " + "4")
print("Environment and Sustainability" + "                  " + "3")
print("Capstone Design" + "                                 " + "1")
print("Undergraduate Research" + "                          " + "1")
print("Seminar on special topics in emerging areas" + "     " + "1")
print("DevOps Engineering practice" + "                     " + "3")
print("Advanced Database Mmanagement Systems" + "           " + "3")
print("Career Skills for IT professionals" + "              " + "3")
print("Communication Skills for Global professionals" + "   " + "3")
